name: CI Optimized

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      timeout-minutes: 10
      
    - name: Run optimized linting
      run: npm run lint:ci
      timeout-minutes: 60
      
    - name: Run type check
      run: npm run type-check
      timeout-minutes: 60
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
      timeout-minutes: 15
      
    - name: Run health check
      run: ./scripts/ci-cd-health-check.sh
      timeout-minutes: 5

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      timeout-minutes: 10
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      timeout-minutes: 30
